-- MySQL Script generated by MySQL Workbench
-- Wed Sep 30 12:48:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema motosalon
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema motosalon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema motosalon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `motosalon` DEFAULT CHARACTER SET utf8 ;
USE `motosalon` ;

-- -----------------------------------------------------
-- Table `motosalon`.`description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motosalon`.`description` (
  `id_description` INT(11) NOT NULL AUTO_INCREMENT,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id_description`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `motosalon`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motosalon`.`role` (
  `id_role` INT(11) NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_role`),
  UNIQUE INDEX `role_name_UNIQUE` (`role_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `motosalon`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motosalon`.`user` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(120) NOT NULL,
  `role` INT(11) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC),
  INDEX `user_role_idx` (`role` ASC),
  CONSTRAINT `user_role`
    FOREIGN KEY (`role`)
    REFERENCES `motosalon`.`role` (`id_role`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `motosalon`.`producer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motosalon`.`producer` (
  `id_producer` INT(11) NOT NULL AUTO_INCREMENT,
  `producer_name` VARCHAR(60) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telephone_number` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_producer`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `producer_name_UNIQUE` (`producer_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `motosalon`.`product_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motosalon`.`product_type` (
  `id_product_type` INT(11) NOT NULL AUTO_INCREMENT,
  `product_type` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_product_type`),
  UNIQUE INDEX `product_type_UNIQUE` (`product_type` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `motosalon`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motosalon`.`product` (
  `id_product` INT(11) NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `product_code` VARCHAR(45) NOT NULL,
  `description` INT(11) NULL DEFAULT NULL,
  `product_type` INT(11) NOT NULL,
  `prise` DOUBLE NULL,
  PRIMARY KEY (`id_product`),
  UNIQUE INDEX `product_code_UNIQUE` (`product_code` ASC),
  INDEX `product_description_idx` (`description` ASC),
  INDEX `product_type_idx` (`product_type` ASC),
  CONSTRAINT `product_description`
    FOREIGN KEY (`description`)
    REFERENCES `motosalon`.`description` (`id_description`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `product_type`
    FOREIGN KEY (`product_type`)
    REFERENCES `motosalon`.`product_type` (`id_product_type`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `motosalon`.`order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motosalon`.`order_status` (
  `id_status` INT(11) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_status`),
  UNIQUE INDEX `status_UNIQUE` (`status` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `motosalon`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motosalon`.`order` (
  `id_order` INT(11) NOT NULL AUTO_INCREMENT,
  `producer` INT(11) NOT NULL,
  `product` INT(11) NOT NULL,
  `order_time` DATETIME NOT NULL,
  `customer` INT(11) NOT NULL,
  `status` INT(11) NOT NULL,
  `quantity` INT(11) NULL DEFAULT NULL,
  `description` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_order`),
  INDEX `order_producer_idx` (`producer` ASC),
  INDEX `order_status_idx` (`status` ASC),
  INDEX `product_idx` (`product` ASC),
  INDEX `order_customer_idx` (`customer` ASC),
  INDEX `order_description_idx` (`description` ASC),
  CONSTRAINT `order_customer`
    FOREIGN KEY (`customer`)
    REFERENCES `motosalon`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `order_description`
    FOREIGN KEY (`description`)
    REFERENCES `motosalon`.`description` (`id_description`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `order_producer`
    FOREIGN KEY (`producer`)
    REFERENCES `motosalon`.`producer` (`id_producer`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `order_product`
    FOREIGN KEY (`product`)
    REFERENCES `motosalon`.`product` (`id_product`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `order_status`
    FOREIGN KEY (`status`)
    REFERENCES `motosalon`.`order_status` (`id_status`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
